config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :paintings
end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>
<ul>
  <% @artists.each do |artist| %>
    <li>
      <p><%= artist.name %></p>
      <ul>
        <% artist.paintings.each do |painting| %>
          <li><%= painting.title %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to "Create a new artist", new_artist_path %>

app/views/artists/new.html.erb
<% if @artist.errors.any? %>
  <ul class="errors">
    <%= @artist.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Add Artist" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtierGallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>